name: Deploy to GitHub Pages

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/

      - uses: actions/deploy-pages@v4
