name: Deploy Widgets

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy-github-pages:
    uses: ./.github/workflows/deploy-github-pages.yml
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: pages
      cancel-in-progress: false

  deploy-vps:
    uses: ./.github/workflows/deploy-vps.yml
    needs: build
    secrets: inherit
